// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vogfylbbqvlwkpkzyiag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZ2Z5bGJicXZsd2twa3p5aWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTA2ODksImV4cCI6MjA2NjM2NjY4OX0.-24q8wY5Hyr9qSX1TGcF9w-_gujf4ig1wZgkORzBBzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);